
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ant-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
